version: '3.8'

services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: whatsapp-clone
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - whatsapp-clone
  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: defadmin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/whatsapp-clone
      KC_DB_SCHEMA: keycloak_schema
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: password
    networks:
      - whatsapp-clone
    command:
      - "start-dev"

networks:
  whatsapp-clone:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local

